# -*- coding: utf-8 -*-
"""Exp 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBqVoK84sSkZvZHGuBqIXhld5MT36MGx
"""

import matplotlib.pyplot as plt

import pandas as pd
df = pd.read_csv("titanic.csv")

#1
df['Pclass'].value_counts().plot(kind='bar')
plt.xlabel("Passenger Class")
plt.ylabel("Count")
plt.title("Passenger Count by Class")
plt.show()

#2
df['Age'].hist(bins=20)
plt.xlabel("Age")
plt.ylabel("Count")
plt.title("Age Distribution of Passengers")
plt.show()

#3
df['Survived'].value_counts().plot(kind='pie', autopct="%1.1f%%")
plt.title("Survival Proportion")
plt.ylabel("")     # remove y-label
plt.show()







import pandas as pd
df = pd.read_csv("Iris.csv")

df.head()

#4
# Convert species names to numerical categories for coloring
species_numeric = pd.factorize(df['Species'])[0]

plt.scatter(df['SepalLengthCm'], df['SepalWidthCm'], c=species_numeric)
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Sepal Length vs Width (Colored by Species)")
plt.show()

#5
df['PetalLengthCm'].hist(bins=20)
plt.xlabel("Petal Length")
plt.ylabel("Count")
plt.title("Petal Length Distribution")
plt.show()

#6
avg_pw = df.groupby('Species')['PetalWidthCm'].mean()

avg_pw.plot(kind='bar')
plt.xlabel("Species")
plt.ylabel("Average Petal Width")
plt.title("Avg Petal Width by Species")
plt.show()



import pandas as pd
df = pd.read_csv("boston.csv")

df.head()

#7
plt.scatter(df['rm'], df['medv'])
plt.xlabel("Average Rooms (RM)")
plt.ylabel("Median Value (MEDV)")
plt.title("RM vs MEDV")
plt.show()

#8
df['age'].hist(bins=20)
plt.xlabel("AGE")
plt.ylabel("Count")
plt.title("Distribution of AGE")
plt.show()

#9
df['chas'].value_counts().plot(kind='bar')
plt.xlabel("Chas (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.title("Chas Value Counts")
plt.show()

import pandas as pd
df = pd.read_csv("winequality-red.csv")
df.head()

#10
df = pd.read_csv("winequality-red.csv")

df.head()

plt.scatter(df['alcohol'], df['quality'])
plt.xlabel("Alcohol")
plt.ylabel("Quality")
plt.title("Alcohol vs Quality")
plt.show()

#11
df['pH'].hist(bins=20)
plt.xlabel("Hue")
plt.ylabel("Count")
plt.title("Hue Distribution")
plt.show()

#12
avg_alcohol = df.groupby('quality')['alcohol'].mean()

avg_alcohol.plot(kind='bar')
plt.xlabel("Quality")
plt.ylabel("Average Alcohol")
plt.title("Average Alcohol by Quality Score")
plt.show()